modLoader = "javafml"
loaderVersion = "[${neoforge_loaderVersion},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wands"
version = "${version}"
displayName = "Building Wands"
authors = "nicguzzo"
description = '''
Building Wands!
'''
#logoFile = ""

[[dependencies.wands]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version} ,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wands]]
modId = "${forge_cloth_config}"
mandatory = true
ordering = "AFTER"
versionRange = "[${cloth_config_version},)"

