name: Build and Release Artifacts for 1.20.1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make build script executable
      run: chmod +x ./build.sh

    - name: Run build script for 1.20.1
      run: ./build.sh 1.20.1

    - name: Upload Artifacts for 1.20.1
      uses: actions/upload-artifact@v3
      with:
        name: compiled-mods-1.20.1
        path: |
          versions/mc1.20.1/fabric/build/libs/*.jar
          versions/mc1.20.1/forge/build/libs/*.jar
